apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-dep
  labels:
    app: auth-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-app
  template:
    metadata:
      name: kanji-up-auth-pod
      labels:
        app: auth-app
    spec:
      imagePullSecrets:
        - name: kanji-up-reco-secret
      containers:
        - name: kanji-up-auth
          image: alexandreem22/auth:0.1
          imagePullPolicy: Always
          readinessProbe:
            httpGet:
              path: /api
              port: 3000
              httpHeaders:
                - name: Host
                  value: kanjiup-auth.alexandre-em.fr
          ports:
            - containerPort: 3000
          envFrom:
            - secretRef:
                name: auth-secret
